version: '3.8'
services:
  php:
    build:
      context: './php'
      args:
        - PHP_VERSION=${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
        - APACHE_VERSION=${APACHE_VERSION}
    networks:
      - backend
      - frontend
    depends_on:
      - php
    ports:
      - '8080:80'
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
networks:
  backend:
  frontend:
